version: "3.9"

services:
  backend:
    container_name: churn-backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    image: churn-backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts   # backend loads model from here
    environment:
      - ARTIFACTS_PATH=/app/artifacts

  frontend:
    container_name: churn-frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: churn-frontend:latest
    restart: always
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
